last_change = 2026-09-09T16:15:38.318523Z
addr = 0x28e5c0
size = 0x14bf
name = "CNetChan_ParseMessagesDemoInternal"

[header]
name = "CNetChan_ParseMessagesDemoInternal"
addr = 0x28e5c0

[header.args]
