last_change = 2026-09-09T16:15:38.318589Z
addr = 0x2a9f40
size = 0x286
name = "CNetworkMessages_FindNetworkMessagePartial"

[header]
name = "CNetworkMessages_FindNetworkMessagePartial"
addr = 0x2a9f40

[header.args]
