last_change = 2026-09-09T16:15:38.318565Z
addr = 0x2a5a60
size = 0x61b
name = "CNetworkMessages_RegisterNetworkFieldSerializer"

[header]
name = "CNetworkMessages_RegisterNetworkFieldSerializer"
addr = 0x2a5a60

[header.args]
